Repository nextcloud/user_saml, pull requests merged in 2018-03, with the labels that each got.

#191 Detect disabled user stable13
  .drone.yml
  appinfo/app.php
  appinfo/routes.php
  lib/Controller/SAMLController.php
  tests/unit/AppInfo/RoutesTest.php
  tests/unit/Controller/SAMLControllerTest.php
Labels: 3. to review

#194 [stable13] try to lookup a user if the uid does not resolve and autoprov is disa…
  lib/Controller/SAMLController.php
  tests/unit/Controller/SAMLControllerTest.php
Labels: 3. to review

#193 Add support for mapping the quota
  lib/Settings/Admin.php
  lib/UserBackend.php
  tests/unit/Settings/AdminTest.php
  tests/unit/UserBackendTest.php
Labels: 2. developing, enhancement

#195 [stable13] Support quota
  lib/Settings/Admin.php
  lib/UserBackend.php
  tests/unit/Settings/AdminTest.php
  tests/unit/UserBackendTest.php
Labels: 3. to review, enhancement

#192 try to lookup a user if the uid does not resolve and autoprov is disabled
  lib/Controller/SAMLController.php
  tests/unit/Controller/SAMLControllerTest.php
Labels: 3. to review

#196 Multiple user back ends
  appinfo/app.php
  appinfo/routes.php
  css/admin.css
  css/selectUserBackEnd.css
  lib/Controller/SAMLController.php
  lib/Settings/Admin.php
  templates/selectUserBackEnd.php
  tests/unit/AppInfo/RoutesTest.php
  tests/unit/Controller/SAMLControllerTest.php
  tests/unit/Settings/AdminTest.php
Labels: 3. to review

#199 Multiple user back ends stable13
  appinfo/app.php
  appinfo/routes.php
  css/admin.css
  css/selectUserBackEnd.css
  lib/Controller/SAMLController.php
  lib/Settings/Admin.php
  templates/selectUserBackEnd.php
  tests/unit/AppInfo/RoutesTest.php
  tests/unit/Controller/SAMLControllerTest.php
  tests/unit/Settings/AdminTest.php
Labels: 3. to review

#198 [stable11] try to lookup a user if the uid does not resolve and autoprov is disables
  lib/Controller/SAMLController.php
  tests/unit/Controller/SAMLControllerTest.php
Labels: 3. to review

#197 [stable12] try to lookup a user if the uid does not resolve and autoprov is disabled
  lib/Controller/SAMLController.php
  tests/unit/Controller/SAMLControllerTest.php
Labels: 3. to review

#163 Use authoriative autoloader
  3rdparty/composer.json
  3rdparty/vendor/composer/ClassLoader.php
  3rdparty/vendor/composer/LICENSE
  3rdparty/vendor/composer/autoload_real.php
Labels: 3. to review

#185 Group mapping
  appinfo/app.php
  lib/Settings/Admin.php
  lib/UserBackend.php
  tests/unit/Settings/AdminTest.php
  tests/unit/UserBackendTest.php
Labels: 3. to review, enhancement
