Repository nextcloud/user_saml, pull requests merged in 2018-08, with the labels that each got.

#214 Allow to configure multiple providers
  appinfo/app.php
  appinfo/routes.php
  css/admin.css
  js/admin.js
  lib/Controller/SAMLController.php
  lib/Controller/SettingsController.php
  lib/SAMLSettings.php
  lib/Settings/Admin.php
  lib/UserBackend.php
  templates/admin.php
  templates/selectUserBackEnd.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/unit/AppInfo/RoutesTest.php
  tests/unit/Controller/SAMLControllerTest.php
  tests/unit/Settings/AdminTest.php
  tests/unit/UserBackendTest.php
Labels: 3. to review, enhancement

#235 we only allow multiple user back ends in combination with SAML, not with environment variables
  lib/Controller/SAMLController.php
  lib/Settings/Admin.php
  templates/admin.php
  tests/unit/Settings/AdminTest.php
Labels: bug

#238 make sure that we don't show the "select user back-end login screen if authentication over environment variables has been chosen
  lib/SAMLSettings.php
Labels: 3. to review

#239 Prepare 1.6.2
  CHANGELOG.md
  Makefile
  appinfo/info.xml
  screenshots/2.png
Labels: 3. to review
