Repository nextcloud/user_saml, pull requests merged in 2019-05, with the labels that each got.

#319 user search parity as with local users
  lib/UserBackend.php
Labels: 3. to review, bug, enhancement

#331 Catch exception during parameter fetching
  appinfo/app.php
Labels: 3. to review, bug

#335 Load a timezone file if no timezone is set
  appinfo/routes.php
  js/timezone.js
  lib/AppInfo/Application.php
  lib/Controller/TimezoneController.php
  tests/unit/AppInfo/RoutesTest.php
Labels: 3. to review

#336 Bump php-saml to 3.1.1
  3rdparty/vendor/composer/installed.json
  3rdparty/vendor/onelogin/php-saml/CHANGELOG
  3rdparty/vendor/onelogin/php-saml/README.md
  3rdparty/vendor/onelogin/php-saml/composer.json
  3rdparty/vendor/onelogin/php-saml/settings_example.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/Auth.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/LogoutRequest.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/Response.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/Utils.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/version.json
Labels: 3. to review

#332 Make NameIDFormat configurable
  js/admin.js
  lib/SAMLSettings.php
  lib/Settings/Admin.php
  templates/admin.php
  tests/unit/Settings/AdminTest.php
Labels: 3. to review
