Repository nextcloud/user_saml, pull requests merged in 2019-06, with the labels that each got.

#338 Fix testing on forks
  .drone.yml
Labels: 3. to review, bug

#334 fix IDP-initiated Logout
  lib/Controller/SAMLController.php
Labels: 3. to review, enhancement, high

#340 Handle SLO logout requests from IdP via POST
  appinfo/routes.php
  lib/Controller/SAMLController.php
  tests/unit/AppInfo/RoutesTest.php
Labels: 3. to review, bug, high
