Repository nextcloud/user_saml, pull requests merged in 2020-11, with the labels that each got.

#476 redirects to homepage instead showing error on blank page
  lib/AppInfo/Application.php
  lib/Middleware/OnlyLoggedInMiddleware.php
  tests/unit/Middleware/OnlyLoggedInMiddlewareTest.php
Labels: 3. to review, bug, enhancement

#480 fix missing user_saml.Idp session value which SAMLSettings rely on
  js/admin.js
  lib/Controller/SAMLController.php
Labels: 3. to review, bug

#486 fixes provisioning of userids from encoded (objectguid) values
  lib/UserBackend.php
Labels: 3. to review, bug

#468 Fix incorrect key name in "Login flow fix"
  lib/Controller/SAMLController.php
Labels: 3. to review, bug

#490 Remove obsolete update.php
  appinfo/update.php
Labels: 3. to review, technical debt
