Repository nextcloud/user_saml, pull requests merged in 2020-09, with the labels that each got.

#439 make "Login options" translatable
  templates/selectUserBackEnd.php
Labels: 3. to review, bug, papercut

#436 Ignore the oauth token path in login with the environment variables
  appinfo/app.php
Labels: 3. to review, bug

#442 >=3.1.3 to become compatible with 18 only
  .drone.yml
  appinfo/info.xml
Labels: 4. to release

#443 bump version to 3.2.0 and drop 18 support
  .drone.yml
  appinfo/info.xml
Labels: 3. to review

#407 Sabre/DAV 4.0: beforeMethod is now beforeMethod:*
  lib/DavPlugin.php
Labels: 4. to release

#445 Bump version, require 20, adjust integration tests
  .drone.yml
  appinfo/info.xml
  tests/integration/features/EnvironmentVariable.feature
  tests/integration/features/Shibboleth.feature
Labels: 3. to review

#444 3.2 series is now 19 only
  .drone.yml
  appinfo/info.xml
Labels: 3. to review

#446 acs endpoint to always return a RedirectResponse
  lib/Controller/SAMLController.php
Labels: 4. to release, backport-request

#450 actually bump deps
  3rdparty/vendor/composer/autoload_real.php
  3rdparty/vendor/composer/installed.json
  3rdparty/vendor/onelogin/php-saml/CHANGELOG
  3rdparty/vendor/onelogin/php-saml/README.md
  3rdparty/vendor/onelogin/php-saml/advanced_settings_example.php
  3rdparty/vendor/onelogin/php-saml/composer.json
  3rdparty/vendor/onelogin/php-saml/phpunit.xml
  3rdparty/vendor/onelogin/php-saml/settings_example.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/Auth.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/AuthnRequest.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/IdPMetadataParser.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/LogoutRequest.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/LogoutResponse.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/Metadata.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/Response.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/Settings.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/Utils.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/version.json
  3rdparty/vendor/robrichards/xmlseclibs/CHANGELOG.txt
  3rdparty/vendor/robrichards/xmlseclibs/LICENSE
  3rdparty/vendor/robrichards/xmlseclibs/README.md
  3rdparty/vendor/robrichards/xmlseclibs/src/XMLSecEnc.php
  3rdparty/vendor/robrichards/xmlseclibs/src/XMLSecurityDSig.php
  3rdparty/vendor/robrichards/xmlseclibs/src/XMLSecurityKey.php
  3rdparty/vendor/robrichards/xmlseclibs/xmlseclibs.php
Labels: 3. to review

#451 [3.2] actually bump deps
  3rdparty/composer.lock
  3rdparty/vendor/composer/autoload_real.php
  3rdparty/vendor/composer/installed.json
  3rdparty/vendor/onelogin/php-saml/CHANGELOG
  3rdparty/vendor/onelogin/php-saml/README.md
  3rdparty/vendor/onelogin/php-saml/advanced_settings_example.php
  3rdparty/vendor/onelogin/php-saml/composer.json
  3rdparty/vendor/onelogin/php-saml/phpunit.xml
  3rdparty/vendor/onelogin/php-saml/settings_example.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/Auth.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/AuthnRequest.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/IdPMetadataParser.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/LogoutRequest.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/LogoutResponse.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/Metadata.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/Response.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/Settings.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/Utils.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/version.json
  3rdparty/vendor/robrichards/xmlseclibs/CHANGELOG.txt
  3rdparty/vendor/robrichards/xmlseclibs/LICENSE
  3rdparty/vendor/robrichards/xmlseclibs/README.md
  3rdparty/vendor/robrichards/xmlseclibs/src/XMLSecEnc.php
  3rdparty/vendor/robrichards/xmlseclibs/src/XMLSecurityDSig.php
  3rdparty/vendor/robrichards/xmlseclibs/src/XMLSecurityKey.php
  3rdparty/vendor/robrichards/xmlseclibs/xmlseclibs.php
Labels: 3. to review

#452 [3.1] actually bump deps for 3.1
  3rdparty/composer.lock
  3rdparty/vendor/composer/autoload_real.php
  3rdparty/vendor/composer/installed.json
  3rdparty/vendor/onelogin/php-saml/CHANGELOG
  3rdparty/vendor/onelogin/php-saml/README.md
  3rdparty/vendor/onelogin/php-saml/advanced_settings_example.php
  3rdparty/vendor/onelogin/php-saml/composer.json
  3rdparty/vendor/onelogin/php-saml/phpunit.xml
  3rdparty/vendor/onelogin/php-saml/settings_example.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/Auth.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/AuthnRequest.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/IdPMetadataParser.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/LogoutRequest.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/LogoutResponse.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/Metadata.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/Response.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/Settings.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/Utils.php
  3rdparty/vendor/onelogin/php-saml/src/Saml2/version.json
  3rdparty/vendor/robrichards/xmlseclibs/CHANGELOG.txt
  3rdparty/vendor/robrichards/xmlseclibs/LICENSE
  3rdparty/vendor/robrichards/xmlseclibs/README.md
  3rdparty/vendor/robrichards/xmlseclibs/src/XMLSecEnc.php
  3rdparty/vendor/robrichards/xmlseclibs/src/XMLSecurityDSig.php
  3rdparty/vendor/robrichards/xmlseclibs/src/XMLSecurityKey.php
  3rdparty/vendor/robrichards/xmlseclibs/xmlseclibs.php
Labels: 3. to review

#458 Handle failing SLO
  lib/Controller/SAMLController.php
Labels: 3. to review
