Repository nextcloud/user_saml, pull requests merged in 2020-10, with the labels that each got.

#463 Fix login flow with SAML
  appinfo/info.xml
  lib/Controller/SAMLController.php
Labels: 3. to review, backport-request, bug

#432 optional possibility to provide a URL for SLO Response
  lib/Controller/SettingsController.php
  lib/SAMLSettings.php
  templates/admin.php
Labels: 3. to review, enhancement

#466 Add checked user id to InvalidArgumentException
  lib/Controller/SAMLController.php
Labels: 3. to review, bug
