Repository nextcloud/user_saml, pull requests merged in 2022-12, with the labels that each got.

#677 Use session locking to be compatible with Nextcloud 25 during logout
  lib/Controller/SAMLController.php
Labels: backport-request

#664 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#683 gently handle incoming SAML Logout Request when the session is missing
  lib/Controller/SAMLController.php
Labels: bug, 3. to review

#685 5.1.2
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review
