Repository nextcloud/user_saml, pull requests merged in 2022-04, with the labels that each got.

#558 Move SAML configurations to a table of their own
  CHANGELOG.md
  appinfo/app.php
  appinfo/info.xml
  appinfo/routes.php
  js/admin.js
  lib/AppInfo/Application.php
  lib/Command/ConfigCreate.php
  lib/Command/ConfigDelete.php
  lib/Command/ConfigGet.php
  lib/Command/ConfigSet.php
  lib/Command/GetMetadata.php
  lib/Controller/SAMLController.php
  lib/Controller/SettingsController.php
  lib/DavPlugin.php
  lib/Db/ConfigurationsEntity.php
  lib/Db/ConfigurationsMapper.php
  lib/Migration/Version5000Date20211025124248.php
  lib/SAMLSettings.php
  lib/Settings/Admin.php
  lib/UserBackend.php
  lib/UserData.php
  templates/admin.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/unit/AppInfo/RoutesTest.php
  tests/unit/Command/GetMetadataTest.php
  tests/unit/Settings/AdminTest.php
  tests/unit/phpunit.xml
Labels: enhancement, 3. to review, pending documentation

#591 l10n: Change place of dot
  lib/Settings/Admin.php
  tests/unit/Settings/AdminTest.php
Labels: bug, 4. to release

#582 change displayName with IEventDispatcher + fixed tests
  appinfo/app.php
  lib/UserBackend.php
  tests/unit/UserBackendTest.php
Labels: bug, 4. to release

#588 Set proper relaystate url
  lib/Controller/SAMLController.php
Labels: bug, 3. to review

#571 Import jstz.min.js from jstimezonedetect 1.0.7
  js/vendor/jstz.min.js
  lib/AppInfo/Application.php
Labels: bug, 4. to release, regression

#586 Create Readme
  README.md
Labels: 3. to review

#604 build and publish services expects user_saml.tar.gz
  Makefile
Labels: 3. to review

#608 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies
