Repository nextcloud/user_saml, pull requests merged in 2022-11, with the labels that each got.

#665 Updating lint-php-cs.yml workflow from template
  .github/workflows/lint-php-cs.yml
Labels: dependencies

#670 add user filtering caps by group memberships
  appinfo/routes.php
  css/admin.css
  js/admin.js
  lib/Controller/SAMLController.php
  lib/Exceptions/UserFilterViolationException.php
  lib/SAMLSettings.php
  lib/Settings/Admin.php
  lib/UserData.php
  templates/admin.php
  templates/notPermitted.php
  tests/unit/Controller/SAMLControllerTest.php
  tests/unit/Settings/AdminTest.php
Labels: enhancement, 3. to review

#672 user filtering only applicable with autoprov
  lib/Controller/SAMLController.php
  tests/unit/Controller/SAMLControllerTest.php
Labels: 3. to review

#674 v5.1.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review
