Repository nextcloud/user_saml, pull requests merged in 2023-11, with the labels that each got.

#776 chore(release): Bump version to 5.2.3
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#778 [stable-5.2] fix(firstLogin): use compatible GenericEvent
  lib/UserBackend.php
Labels: bug, 3. to review, regression

#779 fix(backend): remove deprecated event and class
  appinfo/app.php
  lib/Controller/SAMLController.php
  lib/UserBackend.php
  tests/unit/Controller/SAMLControllerTest.php
  tests/unit/UserBackendTest.php
Labels: 3. to review, technical debt

#781 meta(release): 5.2.4
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#782 chore(cleanup): prepare for 28 availability
  CHANGELOG.md
  appinfo/app.php
  lib/Controller/SAMLController.php
  lib/Controller/SettingsController.php
  lib/Controller/TimezoneController.php
  lib/Middleware/OnlyLoggedInMiddleware.php
  lib/SAMLSettings.php
  lib/Settings/Admin.php
  lib/UserBackend.php
  lib/UserData.php
  tests/psalm-baseline.xml
Labels: 3. to review, technical debt

#787 feat(dep): NC 29 comaptibility
  appinfo/info.xml
Labels: 3. to review

#788 refactor(Controller): read parameter only once
  lib/Controller/SAMLController.php
  tests/unit/Controller/SAMLControllerTest.php
Labels: 4. to release, backport-request, technical debt

#789 6.0.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#790 [stable-5.2] refactor(Controller): read parameter only once
  lib/Controller/SAMLController.php
  tests/unit/Controller/SAMLControllerTest.php
Labels: 3. to review, technical debt

#791 [stable-5.1] refactor(Controller): read parameter only once
  .drone.yml
  .github/workflows/phpunit-sqlite.yml
  appinfo/info.xml
  lib/Controller/SAMLController.php
  tests/unit/Controller/SAMLControllerTest.php
Labels: 2. developing, technical debt

#793 5.1.5
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#792 5.2.5
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review
