Repository nextcloud/user_saml, pull requests merged in 2023-07, with the labels that each got.

#744 chore(CI): Sign .drone.yml file
  .drone.yml
Labels: 3. to review

#732 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  composer.json
  tests/unit/Controller/SAMLControllerTest.php
  tests/unit/Settings/AdminTest.php
  tests/unit/UserBackendTest.php
Labels: 3. to review, dependencies, automated

#748 meta(release): 5.2.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#747 ci: Add psalm
  .github/workflows/psalm.yml
  .gitignore
  composer.json
  composer.lock
  psalm.xml
  tests/psalm-baseline.xml
  tests/stub.phpstub
Labels: 3. to review

#754 Fix validating SAML XML schemas
  lib/Command/GetMetadata.php
  lib/Controller/SAMLController.php
  lib/Helper/TXmlHelper.php
Labels: bug, 4. to release

#756 [stable-5.1] fix(saml): enable xml entity loader where necessary
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  lib/Command/GetMetadata.php
  lib/Controller/SAMLController.php
  lib/Helper/TXmlHelper.php
Labels: bug, 3. to review

#759 meta(release): 5.2.2
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#762 [stable-3.3] build(make): fix Makefile for release building
  Makefile
Labels: 3. to review
