Repository nextcloud/user_saml, pull requests merged in 2023-10, with the labels that each got.

#769 fix(login): do not hardcode IdP to 1 on redirect
  appinfo/app.php
Labels: bug, 3. to review, backport-request

#771 fix: Implement IGetDisplayNameBackend
  lib/UserBackend.php
Labels: 4. to release

#773 fix: Implement IGetDisplayNameBackend
  lib/UserBackend.php
Labels: bug, 3. to review

#774 fix: Do not try to validate metadata for environment variable config
  js/admin.js
Labels: bug, 3. to review, backport-request
