Repository nextcloud/user_saml, pull requests merged in 2024-10, with the labels that each got.

#888 fix(Groups): drop groups with mixed users from transition list
  lib/GroupManager.php
  lib/Jobs/MigrateGroups.php
  tests/integration/features/Shibboleth.feature
  tests/integration/features/bootstrap/FeatureContext.php
Labels: bug, 3. to review

#893 fix(command): Ensure that writeln() argument is string
  lib/Command/ConfigCreate.php
Labels: bug, 3. to review

#886 fix: Log attribute updates
  lib/UserBackend.php
  tests/unit/UserBackendTest.php
Labels: 3. to review

#889 debug(Groups): log group handling upon login
  lib/GroupManager.php
Labels: 3. to review

#895 build(release): 6.3.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#896 refactor: small adjustements not impacting functionalities
  lib/Controller/SAMLController.php
Labels: 3. to review, refactor
