Repository nextcloud/user_saml, pull requests merged in 2024-01, with the labels that each got.

#799 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
Labels: 3. to review, dependencies, automated

#801 6.1.0 RC1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#802 meta(release): 6.1.0
  appinfo/info.xml
Labels: 3. to review

#803 meta(release): 5.2.6
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#806 Fix: keep local groups when there is no group mapping set up
  lib/GroupManager.php
  tests/integration/features/Shibboleth.feature
  tests/unit/GroupManagerTest.php
Labels: bug, 4. to release, regression
