Repository nextcloud/user_saml, pull requests merged in 2024-03, with the labels that each got.

#816 fix(UI): permanent labels for input elements
  css/admin.css
  templates/admin.php
Labels: bug, 3. to review

#818 [stable-5.2] fix(upgrade): exception when upgrading from 27 to 28
  lib/AppInfo/Application.php
  tests/stub.phpstub
Labels: bug, 3. to review, regression

#819 fix(User): load timezone handling related resources
  lib/AppInfo/Application.php
  tests/integration/features/bootstrap/FeatureContext.php
Labels: bug, 3. to review, regression

#821 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#822 build(release): 5.2.7
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#823 build(release): 6.1.2
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review
