Repository nextcloud/user_saml, pull requests merged in 2024-12, with the labels that each got.

#855 feat(groups): add setting display name to group backend
  lib/GroupBackend.php
Labels: enhancement, 4. to release, feedback-requested

#912 deps(php-saml): apply PHP 8.4 compat patch
  composer.json
  composer.lock
Labels: bug, 3. to review, dependencies

#907 refactor: Apply code best practices PHP8+
  lib/Command/ConfigCreate.php
  lib/Command/ConfigDelete.php
  lib/Command/ConfigGet.php
  lib/Command/ConfigSet.php
  lib/Command/GetMetadata.php
  lib/Controller/SettingsController.php
  lib/Controller/TimezoneController.php
  lib/DavPlugin.php
  lib/GroupManager.php
  lib/Jobs/MigrateGroups.php
  lib/Middleware/OnlyLoggedInMiddleware.php
  lib/Migration/RememberLocalGroupsForPotentialMigrations.php
  lib/SAMLSettings.php
  lib/Settings/Admin.php
  lib/Settings/Section.php
  lib/UserBackend.php
  lib/UserData.php
Labels: 3. to review, refactor

#913 fix(UI): fix usage of $.ajax by going VanillaJS
  js/admin.js
Labels: bug, 3. to review

#914 build(release): 6.4.0
  .php_cs-fixer.dist.php
  CHANGELOG.md
  Makefile
  appinfo/info.xml
Labels: 3. to review

#910 Handle LoginException when authenticating with Apache
  appinfo/app.php
  tests/integration/features/EnvironmentVariable.feature
  tests/integration/features/bootstrap/FeatureContext.php
Labels: bug, 2. developing

#859 ci: switch to any github runner again
  .github/workflows/integration.yml
Labels: 4. to release

#915 build(release): 6.4.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review
