Repository nextcloud/user_saml, pull requests merged in 2024-04, with the labels that each got.

#829 fix(Login): do not advertise CHECK_PASSWORD capability
  lib/UserBackend.php
Labels: bug, 3. to review

#831 build(release): 6.1.3
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#836 Updating appstore-build-publish.yml workflow from template
  .github/workflows/appstore-build-publish.yml
Labels: dependencies

#835 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#837 test(ci): update integration test to server reqs
  .github/workflows/integration.yml
Labels: 3. to review

#834 perf(db): Avoid double querying
  lib/UserBackend.php
Labels: 3. to review
