Repository nextcloud/user_saml, pull requests merged in 2024-07, with the labels that each got.

#856 feat: migrate from deprecated PublicEmitter to IEventDispatcher
  lib/GroupManager.php
  tests/stub.phpstub
  tests/unit/GroupManagerTest.php
Labels: feedback-requested

#863 fix(Groups): take over members during migration
  appinfo/info.xml
  lib/Command/ConfigDelete.php
  lib/Command/GroupMigrationCopyIncomplete.php
  lib/GroupManager.php
  lib/Jobs/MigrateGroups.php
  lib/Migration/RememberLocalGroupsForPotentialMigrations.php
  lib/Migration/TransferGroupMembers.php
  lib/Service/GroupMigration.php
  tests/integration/features/Shibboleth.feature
  tests/integration/features/bootstrap/FeatureContext.php
  tests/stub.phpstub
Labels: bug, 3. to review

#866 build(Release): 6.2.0
  CHANGELOG.md
Labels: 3. to review

#809 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
Labels: 3. to review, dependencies, automated
